const KEYS={accounts:'portion_accounts_v2',posts:'portion_posts_v2',messages:'portion_messages_v1',session:'portion_session_v2'};
let role='',user=sessionStorage.getItem(KEYS.session)||'',authMode='login',pendingWrite='',verifyTarget=null,chatTarget=null;
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const get=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}},put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const safe=s=>{const d=document.createElement('div');d.textContent=s;return d.innerHTML};
const hash=s=>btoa(unescape(encodeURIComponent(s)));
function seedAdmin(){const accounts=get(KEYS.accounts);if(!accounts.some(a=>a.username.toLowerCase()==='admin')){accounts.push({username:'admin',password:hash('Admin!2026'),role:'admin'});put(KEYS.accounts,accounts)}}
const isAdmin=()=>user.toLowerCase()==='admin';
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function modal(id,on){$('#'+id).classList.toggle('open',on)}
function updateUser(){ $('#loginBtn').textContent=user?`${user} · 로그아웃`:'로그인';$('#messagesBtn').hidden=!user;if(role)render() }
function selectRole(next){role=next;$('#roleScreen').hidden=true;$('#appScreen').hidden=false;$('#changeRole').hidden=false;const carrier=role==='carrier';$('#roleLabel').textContent=carrier?'CARRIER DASHBOARD':'SHIPPER DASHBOARD';$('#heroTitle').innerHTML=carrier?'남는 선복을<br>새로운 기회로 바꾸세요.':'같은 목적지의 화주와<br>함께 더 가볍게 보내세요.';$('#heroText').textContent=carrier?'남는 컨테이너 공간을 등록하고, 운송 이용자의 화물을 받아보세요.':'필요한 화물을 등록하고, 목적지가 같은 공동운송을 찾아보세요.';$('#freightTitle').textContent=carrier?'운송 공간 모집글':'화물 공동운송 모집글';render()}
function requireUser(action){if(user)return action();pendingWrite=action;authMode=get(KEYS.accounts).length?'login':'signup';setAuth();modal('authModal',true)}
function setAuth(){const signup=authMode==='signup';$('#authTitle').textContent=signup?'아이디 만들기':'로그인';$('#confirmWrap').hidden=!signup;$('#authSubmit').textContent=signup?'아이디 만들고 계속하기':'로그인하고 계속하기';$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===authMode));$('#authError').textContent=''}
function render(){const posts=get(KEYS.posts);const freight=posts.filter(x=>x.type==='freight'&&x.role===role),community=posts.filter(x=>x.type==='community');draw('#freightList','#freightEmpty',freight,'freight');draw('#communityList','#communityEmpty',community,'community')}
function draw(list,empty,items,type){$(list).innerHTML=items.map(x=>`<article class="card"><span class="tag">${type==='freight'?(x.role==='carrier'?'운송 공간':'화물 요청'):safe(x.category)}</span><h3>${safe(x.title)}</h3><p>${safe(x.content)}</p><div class="meta">작성자 ${safe(x.author)}</div><div class="actions">${type==='freight'&&x.author!==user?`<button class="message" data-message="${x.id}">1:1 메시지</button>`:''}${x.author===user?`<button data-edit="${x.id}">수정</button><button class="delete" data-delete="${x.id}">삭제</button>`:''}${isAdmin()&&x.author!==user?`<button class="admin-delete" data-admin-delete="${x.id}">관리자 삭제</button>`:''}</div></article>`).join('');$(list).hidden=!items.length;$(empty).hidden=!!items.length}
function openChat(post){chatTarget=post;$('#chatTitle').textContent=`${post.author}님에게 문의`;$('#chatInfo').textContent=`「${post.title}」 모집글에 관한 1:1 메시지입니다.`;$('#chatForm').reset();renderChat();modal('chatModal',true)}
function renderChat(){const messages=get(KEYS.messages).filter(m=>m.postId===chatTarget.id);$('#chatList').innerHTML=messages.length?messages.map(m=>`<div class="bubble ${m.sender===user?'mine':'other'}"><b>${safe(m.sender)}</b><span>${safe(m.text)}</span></div>`).join(''):'<p class="chat-empty">첫 번째 메시지를 보내 보세요.</p>';$('#chatList').scrollTop=$('#chatList').scrollHeight}
function openInbox(){const messages=get(KEYS.messages).filter(m=>m.sender===user||m.recipient===user);const latest={};messages.forEach(m=>{if(!latest[m.postId]||new Date(latest[m.postId].createdAt)<new Date(m.createdAt))latest[m.postId]=m});const rooms=Object.values(latest).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));$('#inboxList').innerHTML=rooms.length?rooms.map(m=>{const post=get(KEYS.posts).find(p=>p.id===m.postId);const other=m.sender===user?m.recipient:m.sender;return `<button class="inbox-item" data-inbox="${m.postId}"><b>${safe(other)}님과의 대화</b><span>${safe(post?.title||'삭제된 모집글')}</span><small>${safe(m.text)}</small></button>`}).join(''):'<p class="chat-empty">아직 받은 메시지나 보낸 메시지가 없어요.</p>';modal('inboxModal',true)}
function openPost(type,post){const f=$('#postForm');f.reset();f.elements.id.value=post?.id||'';$('#postType').textContent=type==='freight'?'FREIGHT POST':'COMMUNITY POST';$('#postTitle').textContent=post?'글 수정':type==='freight'?'모집글 등록':'커뮤니티 글쓰기';$('#categoryWrap').hidden=type==='freight';f.dataset.type=type;if(post){f.title.value=post.title;f.content.value=post.content;f.category.value=post.category||'질문'}modal('postModal',true)}
$$('[data-role]').forEach(b=>b.onclick=()=>selectRole(b.dataset.role));
$('#changeRole').onclick=()=>{$('#appScreen').hidden=true;$('#roleScreen').hidden=false;$('#changeRole').hidden=true};
$('#loginBtn').onclick=()=>{if(user){sessionStorage.removeItem(KEYS.session);user='';updateUser();toast('로그아웃되었습니다.')}else{pendingWrite='';authMode=get(KEYS.accounts).length?'login':'signup';setAuth();modal('authModal',true)}};
$('#messagesBtn').onclick=()=>requireUser(openInbox);
$$('[data-mode]').forEach(b=>b.onclick=()=>{authMode=b.dataset.mode;setAuth()});
$('#writeFreight').onclick=()=>requireUser(()=>openPost('freight'));$('#writeCommunity').onclick=()=>requireUser(()=>openPost('community'));$$('[data-write]').forEach(b=>b.onclick=()=>requireUser(()=>openPost(b.dataset.write)));
$$('[data-close]').forEach(b=>b.onclick=()=>modal(b.dataset.close,false));$$('.overlay').forEach(o=>o.onclick=e=>{if(e.target===o)modal(o.id,false)});
$('#authForm').onsubmit=e=>{e.preventDefault();const f=e.target,u=f.username.value.trim(),p=f.password.value,accounts=get(KEYS.accounts);try{if(!/^[A-Za-z0-9_]{4,20}$/.test(u))throw Error('아이디는 영문·숫자·밑줄 4~20자입니다.');if(authMode==='signup'){if(!(p.length>=8&&/[A-Za-z]/.test(p)&&/\d/.test(p)&&/[^A-Za-z0-9]/.test(p)))throw Error('비밀번호는 8자 이상 영문·숫자·특수문자가 필요합니다.');if(p!==f.confirm.value)throw Error('비밀번호 확인이 다릅니다.');if(accounts.some(a=>a.username.toLowerCase()===u.toLowerCase()))throw Error('이미 사용 중인 아이디입니다.');accounts.push({username:u,password:hash(p)});put(KEYS.accounts,accounts);toast('아이디를 만들었습니다.')}else{const a=accounts.find(a=>a.username.toLowerCase()===u.toLowerCase());if(!a||a.password!==hash(p))throw Error('아이디 또는 비밀번호가 맞지 않습니다.')}user=u;sessionStorage.setItem(KEYS.session,u);updateUser();modal('authModal',false);const a=pendingWrite;pendingWrite='';if(typeof a==='function')a()}catch(err){$('#authError').textContent=err.message}};
$('#postForm').onsubmit=e=>{e.preventDefault();const f=e.target,posts=get(KEYS.posts),now=new Date().toISOString(),data={title:f.title.value.trim(),content:f.content.value.trim(),category:f.category.value};if(f.elements.id.value){const i=posts.findIndex(x=>x.id===f.elements.id.value);posts[i]={...posts[i],...data,updatedAt:now};toast('글을 수정했습니다.')}else{posts.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),type:f.dataset.type,role,author:user,...data,createdAt:now,updatedAt:now});toast('글을 등록했습니다.')}put(KEYS.posts,posts);modal('postModal',false);render()};
document.addEventListener('click',e=>{const inbox=e.target.closest('[data-inbox]'),message=e.target.closest('[data-message]'),adminDelete=e.target.closest('[data-admin-delete]'),edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(inbox){const post=get(KEYS.posts).find(x=>x.id===inbox.dataset.inbox);if(post){modal('inboxModal',false);return openChat(post)}}if(message){const post=get(KEYS.posts).find(x=>x.id===message.dataset.message);return requireUser(()=>openChat(post))}if(adminDelete&&isAdmin()){if(confirm('관리자 권한으로 이 글을 삭제할까요?')){put(KEYS.posts,get(KEYS.posts).filter(x=>x.id!==adminDelete.dataset.adminDelete));render();toast('관리자 권한으로 글을 삭제했습니다.')}return}if(edit||del){const id=(edit||del).dataset.edit||(edit||del).dataset.delete;verifyTarget={id,action:edit?'edit':'delete'};$('#verifyForm').reset();$('#verifyError').textContent='';modal('verifyModal',true)}});
$('#chatForm').onsubmit=e=>{e.preventDefault();const text=e.target.message.value.trim();if(!text||!chatTarget)return;const messages=get(KEYS.messages);messages.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),postId:chatTarget.id,sender:user,recipient:chatTarget.author,text,createdAt:new Date().toISOString()});put(KEYS.messages,messages);e.target.reset();renderChat();toast('메시지를 보냈습니다.')};
$('#verifyForm').onsubmit=e=>{e.preventDefault();const f=e.target,post=get(KEYS.posts).find(x=>x.id===verifyTarget.id),acc=get(KEYS.accounts).find(a=>a.username.toLowerCase()===f.username.value.trim().toLowerCase());if(!post||!acc||post.author.toLowerCase()!==f.username.value.trim().toLowerCase()||acc.password!==hash(f.password.value)){return $('#verifyError').textContent='작성자 아이디 또는 비밀번호가 맞지 않습니다.'}modal('verifyModal',false);if(verifyTarget.action==='delete'){if(confirm('이 글을 삭제할까요?')){put(KEYS.posts,get(KEYS.posts).filter(x=>x.id!==post.id));render();toast('글을 삭제했습니다.')}}else openPost(post.type,post)};
seedAdmin();
updateUser();
