const DB_URL='https://dtycldmusligztcoeaig.supabase.co';
const DB_KEY='sb_publishable_h_Lg2hj8TrBaok1gJuv4og_kvpZglyA';
const db=window.supabase.createClient(DB_URL,DB_KEY);
let role='',user='',userId='',profile={},authMode='login',pendingWrite=null,verifyTarget=null,chatTarget=null,chatPartnerId='',posts=[],messages=[],applications=[],applicationPostId='',realtimeChannel=null;
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const safe=s=>{const d=document.createElement('div');d.textContent=s||'';return d.innerHTML};
const userEmail=name=>`${name.trim().toLowerCase()}@portion-demo.example.com`;
const mediaHTML=media=>{const url=media?.url||media?.data;if(!url)return '';return media.type?.startsWith('video/')?`<video controls src="${safe(url)}" style="width:100%;max-height:260px;border-radius:8px;margin-top:14px"></video>`:`<img src="${safe(url)}" alt="첨부 사진" style="width:100%;max-height:260px;object-fit:cover;border-radius:8px;margin-top:14px">`};
const fileData=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({type:file.type,data:reader.result});reader.onerror=reject;reader.readAsDataURL(file)});
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function modal(id,on){$('#'+id).classList.toggle('open',on)}
function isAdmin(){return profile.role==='admin'}
function updateUser(){ $('#loginBtn').textContent=user?`${user} · 로그아웃`:'로그인';$('#messagesBtn').hidden=!user;if(role)render() }
function startRealtime(){if(realtimeChannel)db.removeChannel(realtimeChannel);if(!userId)return;realtimeChannel=db.channel(`contact-messages-${userId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'direct_messages',filter:`recipient_id=eq.${userId}`},async payload=>{await loadMessages();if(chatTarget&&payload.new.post_id===chatTarget.id)renderChat();$('#messagesBtn').textContent='메시지함 · 새 메시지';toast('새 메시지가 도착했습니다.');}).subscribe()}
async function ensureProfile(authUser){const username=authUser.user_metadata?.username||authUser.email?.split('@')[0]||'user';const {data}=await db.from('profiles').select('*').eq('id',authUser.id).maybeSingle();if(!data){await db.from('profiles').insert({id:authUser.id,username});profile={id:authUser.id,username,role:'user'}}else profile=data;user=profile.username;userId=authUser.id}
async function init(){const {data:{session}}=await db.auth.getSession();if(session){await ensureProfile(session.user);startRealtime()}updateUser();if(role)render()}
function selectRole(next){role=next;$('#roleScreen').hidden=true;$('#appScreen').hidden=false;$('#changeRole').hidden=false;const carrier=role==='carrier';$('#roleLabel').textContent=carrier?'CARRIER DASHBOARD':'SHIPPER DASHBOARD';$('#heroTitle').innerHTML=carrier?'남는 선복을<br>새로운 기회로 바꾸세요.':'같은 목적지의 화주와<br>함께 더 가볍게 보내세요.';$('#heroText').textContent=carrier?'남는 컨테이너 공간을 등록하고, 운송 이용자의 화물을 받아보세요.':'필요한 화물을 등록하고, 목적지가 같은 공동운송을 찾아보세요.';$('#freightTitle').textContent=carrier?'운송 공간 모집글':'화물 공동운송 모집글';render()}
function requireUser(action){if(user)return action();pendingWrite=action;authMode='login';setAuth();modal('authModal',true)}
function setAuth(){const signup=authMode==='signup';$('#authTitle').textContent=signup?'아이디 만들기':'로그인';$('#confirmWrap').hidden=!signup;$('#authSubmit').textContent=signup?'아이디 만들고 계속하기':'로그인하고 계속하기';$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===authMode));$('#authError').textContent=''}
async function loadPosts(){const {data,error}=await db.from('posts').select('*, profiles(username,role)').order('created_at',{ascending:false});if(error){toast('DB 글을 불러오지 못했습니다.');return}posts=(data||[]).map(p=>({...p,author:p.profiles?.username||'알 수 없음',media:p.media_path?{path:p.media_path,type:p.media_type,url:db.storage.from('contact-media').getPublicUrl(p.media_path).data.publicUrl}:null}))}
async function loadApplications(){if(!userId){applications=[];return}const {data,error}=await db.from('freight_applications').select('*, applicant:profiles!freight_applications_applicant_id_fkey(username)').order('created_at',{ascending:false});if(!error)applications=data||[]}
async function render(){await Promise.all([loadPosts(),loadApplications()]);const freight=posts.filter(x=>x.type==='freight'),community=posts.filter(x=>x.type==='community');draw('#freightList','#freightEmpty',freight,'freight');draw('#communityList','#communityEmpty',community,'community')}
function freightAction(x){if(!user||x.author_id===userId)return '';const mine=applications.find(a=>a.post_id===x.id&&a.applicant_id===userId);if(mine)return `<span class="status">${mine.status==='accepted'?'수락 완료':mine.status==='rejected'?'거절됨':'신청 대기 중'}</span>`;if(role==='shipper'&&x.user_role==='carrier')return `<button class="apply" data-apply="${x.id}" data-apply-status="pending">운송 신청하기</button>`;if(role==='carrier'&&x.user_role==='shipper')return `<button class="apply" data-apply="${x.id}" data-apply-status="accepted">이 운송 수락하기</button>`;return ''}
function draw(list,empty,items,type){$(list).innerHTML=items.map(x=>{const ownApplications=applications.filter(a=>a.post_id===x.id);return `<article class="card"><span class="tag">${type==='freight'?(x.user_role==='carrier'?'운송 공간':'화물 요청'):safe(x.category)}</span><h3>${safe(x.title)}</h3><p>${safe(x.content)}</p>${mediaHTML(x.media)}<div class="meta">작성자 ${safe(x.author)}</div><div class="actions">${type==='freight'&&x.author_id!==userId?`<button class="message" data-message="${x.id}">1:1 메시지</button>${freightAction(x)}`:''}${type==='freight'&&x.author_id===userId?`<button data-applications="${x.id}">신청 관리${ownApplications.length?` (${ownApplications.length})`:''}</button>`:''}${x.author_id===userId?`<button data-edit="${x.id}">수정</button><button class="delete" data-delete="${x.id}">삭제</button>`:''}${isAdmin()&&x.author_id!==userId?`<button class="admin-delete" data-admin-delete="${x.id}">관리자 삭제</button>`:''}</div></article>`}).join('');$(list).hidden=!items.length;$(empty).hidden=!!items.length}
async function openApplications(postId){applicationPostId=postId;await loadApplications();const list=applications.filter(a=>a.post_id===postId);$('#applicationList').innerHTML=list.length?list.map(a=>`<div class="application-item"><b>${safe(a.applicant?.username||'신청자')}</b><small>상태: ${a.status==='accepted'?'수락됨':a.status==='rejected'?'거절됨':'대기 중'}</small>${a.status==='pending'?`<div class="actions"><button class="message" data-application-status="accepted" data-application-id="${a.id}">수락</button><button class="delete" data-application-status="rejected" data-application-id="${a.id}">거절</button></div>`:''}</div>`).join(''):'<p class="chat-empty">아직 신청자가 없습니다.</p>';modal('applicationModal',true)}
function openPost(type,post){const f=$('#postForm');f.reset();f.elements.id.value=post?.id||'';f.dataset.type=type;f.dataset.mediaPath=post?.media_path||'';f.dataset.mediaType=post?.media_type||'';$('#postType').textContent=type==='freight'?'FREIGHT POST':'COMMUNITY POST';$('#postTitle').textContent=post?'글 수정':type==='freight'?'모집글 등록':'커뮤니티 글쓰기';$('#categoryWrap').hidden=type==='freight';$('#mediaPreview').innerHTML=mediaHTML(post?.media);$('#mediaError').textContent='';if(post){f.title.value=post.title;f.content.value=post.content;f.category.value=post.category||'질문'}modal('postModal',true)}
async function openChat(post){chatTarget=post;$('#chatForm').reset();await loadMessages();const room=messages.filter(m=>m.post_id===post.id);const latestIncoming=[...room].reverse().find(m=>m.sender_id!==userId);chatPartnerId=post.author_id===userId?latestIncoming?.sender_id||'':post.author_id;const partnerName=post.author_id===userId?(latestIncoming?.sender?.username||'문의한 사용자'):post.author;$('#chatTitle').textContent=`${partnerName}님과의 대화`;$('#chatInfo').textContent=chatPartnerId?`「${post.title}」 모집글에 관한 1:1 메시지입니다.`:'아직 이 모집글에 도착한 문의가 없습니다.';$('#chatForm').hidden=!chatPartnerId;renderChat();modal('chatModal',true)}
async function loadMessages(){if(!userId)return;const {data,error}=await db.from('direct_messages').select('*, sender:profiles!direct_messages_sender_id_fkey(username), recipient:profiles!direct_messages_recipient_id_fkey(username)').or(`sender_id.eq.${userId},recipient_id.eq.${userId}`).order('created_at');if(!error)messages=data||[]}
function renderChat(){const room=messages.filter(m=>m.post_id===chatTarget.id);$('#chatList').innerHTML=room.length?room.map(m=>`<div class="bubble ${m.sender_id===userId?'mine':'other'}"><b>${safe(m.sender?.username||m.recipient?.username)}</b><span>${safe(m.body)}</span></div>`).join(''):'<p class="chat-empty">첫 번째 메시지를 보내 보세요.</p>';$('#chatList').scrollTop=$('#chatList').scrollHeight}
async function openInbox(){await loadMessages();const latest={};messages.forEach(m=>{if(!latest[m.post_id]||new Date(latest[m.post_id].created_at)<new Date(m.created_at))latest[m.post_id]=m});const rooms=Object.values(latest).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$('#inboxList').innerHTML=rooms.length?rooms.map(m=>{const p=posts.find(x=>x.id===m.post_id);const other=m.sender_id===userId?m.recipient?.username:m.sender?.username;return `<button data-inbox="${m.post_id}" style="display:grid;gap:5px;width:100%;margin-top:10px;padding:14px;text-align:left;background:#fff;border:1px solid #d6e1dc;border-radius:9px;color:#142934"><b style="font-size:14px">${safe(other||'상대방')}님과의 대화</b><span style="font-size:13px;font-weight:700">${safe(p?.title||'모집글')}</span><small style="font-size:12px;color:#607276;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${safe(m.body)}</small></button>`}).join(''):'<p class="chat-empty">아직 메시지가 없어요.</p>';modal('inboxModal',true)}
$$('[data-role]').forEach(b=>b.onclick=()=>selectRole(b.dataset.role));
$('#changeRole').onclick=()=>{$('#appScreen').hidden=true;$('#roleScreen').hidden=false;$('#changeRole').hidden=true};
$('#loginBtn').onclick=async()=>{if(user){await db.auth.signOut();if(realtimeChannel)db.removeChannel(realtimeChannel);realtimeChannel=null;user='';userId='';profile={};updateUser();toast('로그아웃되었습니다.')}else{pendingWrite=null;authMode='login';setAuth();modal('authModal',true)}};
$('#messagesBtn').onclick=()=>{ $('#messagesBtn').textContent='메시지함'; requireUser(openInbox) };$$('[data-mode]').forEach(b=>b.onclick=()=>{authMode=b.dataset.mode;setAuth()});
$('#writeFreight').onclick=()=>requireUser(()=>openPost('freight'));$('#writeCommunity').onclick=()=>requireUser(()=>openPost('community'));$$('[data-write]').forEach(b=>b.onclick=()=>requireUser(()=>openPost(b.dataset.write)));
$$('[data-close]').forEach(b=>b.onclick=()=>modal(b.dataset.close,false));$$('.overlay').forEach(o=>o.onclick=e=>{if(e.target===o)modal(o.id,false)});
$('#authForm').onsubmit=async e=>{e.preventDefault();const f=e.target,username=f.username.value.trim(),password=f.password.value;try{if(!/^[A-Za-z0-9_]{4,20}$/.test(username))throw Error('아이디는 영문·숫자·밑줄 4~20자입니다.');if(authMode==='signup'){if(!(password.length>=8&&/[A-Za-z]/.test(password)&&/\d/.test(password)&&/[^A-Za-z0-9]/.test(password)))throw Error('비밀번호는 8자 이상 영문·숫자·특수문자가 필요합니다.');if(password!==f.confirm.value)throw Error('비밀번호 확인이 다릅니다.');const {data,error}=await db.auth.signUp({email:userEmail(username),password,options:{data:{username}}});if(error)throw error;if(data.user)await ensureProfile(data.user);toast('아이디를 만들었습니다.')}else{const {data,error}=await db.auth.signInWithPassword({email:userEmail(username),password});if(error)throw error;await ensureProfile(data.user)}startRealtime();updateUser();modal('authModal',false);const action=pendingWrite;pendingWrite=null;if(action)action()}catch(err){$('#authError').textContent=err.message||'로그인에 실패했습니다.'}};
$('#postForm').onsubmit=async e=>{e.preventDefault();const f=e.target;try{const file=f.elements.media.files[0];let mediaPath=f.dataset.mediaPath||null,mediaType=f.dataset.mediaType||null;if(file){if(!file.type.startsWith('image/')&&!file.type.startsWith('video/'))throw Error('사진 또는 동영상 파일만 올릴 수 있습니다.');if(file.size>3*1024*1024)throw Error('첨부파일은 3MB 이하만 올릴 수 있습니다.');const extension=(file.name.split('.').pop()||'bin').replace(/[^a-zA-Z0-9]/g,'')||'bin';mediaPath=`${userId}/${crypto.randomUUID()}.${extension}`;mediaType=file.type;const {error:uploadError}=await db.storage.from('contact-media').upload(mediaPath,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError}const data={type:f.dataset.type,user_role:role,category:f.category.value,title:f.title.value.trim(),content:f.content.value.trim(),author_id:userId,media_path:mediaPath,media_type:mediaType,updated_at:new Date().toISOString()};let error;if(f.elements.id.value)({error}=await db.from('posts').update(data).eq('id',f.elements.id.value));else({error}=await db.from('posts').insert(data));if(error)throw error;modal('postModal',false);toast('글과 첨부파일을 저장했습니다.');render()}catch(err){$('#mediaError').textContent=err.message||'글을 저장하지 못했습니다.'}};
$('#postForm').elements.media.onchange=async e=>{const file=e.target.files[0];if(!file)return;if((!file.type.startsWith('image/')&&!file.type.startsWith('video/'))||file.size>3*1024*1024){$('#mediaError').textContent='사진·동영상 파일만, 3MB 이하로 올릴 수 있습니다.';e.target.value='';return}$('#mediaError').textContent='';$('#mediaPreview').innerHTML=mediaHTML(await fileData(file))};
document.addEventListener('click',async e=>{const inbox=e.target.closest('[data-inbox]'),message=e.target.closest('[data-message]'),adminDelete=e.target.closest('[data-admin-delete]'),edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(inbox){const post=posts.find(x=>x.id===inbox.dataset.inbox);if(post){modal('inboxModal',false);return openChat(post)}}if(message){const post=posts.find(x=>x.id===message.dataset.message);return requireUser(()=>openChat(post))}if(adminDelete&&isAdmin()){if(confirm('관리자 권한으로 이 글을 삭제할까요?')){await db.from('posts').delete().eq('id',adminDelete.dataset.adminDelete);render();toast('글을 삭제했습니다.')}return}if(edit||del){const id=(edit||del).dataset.edit||(edit||del).dataset.delete;verifyTarget={id,action:edit?'edit':'delete'};$('#verifyForm').reset();$('#verifyError').textContent='';modal('verifyModal',true)}});
async function sendApplication(postId,status){const {error}=await db.from('freight_applications').insert({post_id:postId,applicant_id:userId,status});if(error)return toast(error.code==='23505'?'이미 신청한 모집글입니다.':'신청을 저장하지 못했습니다.');toast(status==='accepted'?'운송을 수락했습니다. 글쓴이와 대화를 이어가세요.':'운송을 신청했습니다. 운송업자의 확인을 기다려 주세요.');render()}
document.addEventListener('click',async e=>{const apply=e.target.closest('[data-apply]'),manage=e.target.closest('[data-applications]'),change=e.target.closest('[data-application-status]');if(apply)return requireUser(()=>sendApplication(apply.dataset.apply,apply.dataset.applyStatus));if(manage)return openApplications(manage.dataset.applications);if(change){const {error}=await db.from('freight_applications').update({status:change.dataset.applicationStatus}).eq('id',change.dataset.applicationId);if(error)return toast('상태를 바꾸지 못했습니다.');toast(change.dataset.applicationStatus==='accepted'?'신청을 수락했습니다.':'신청을 거절했습니다.');await openApplications(applicationPostId);render()}});
$('#chatForm').onsubmit=async e=>{e.preventDefault();const body=e.target.message.value.trim();if(!body||!chatTarget||!chatPartnerId)return;const {error}=await db.from('direct_messages').insert({post_id:chatTarget.id,sender_id:userId,recipient_id:chatPartnerId,body});if(error)return toast('메시지를 보내지 못했습니다.');e.target.reset();await loadMessages();renderChat();toast('메시지를 보냈습니다.')};
$('#verifyForm').onsubmit=async e=>{e.preventDefault();const f=e.target,post=posts.find(x=>x.id===verifyTarget.id);try{if(!post)throw Error('글을 찾을 수 없습니다.');const {data,error}=await db.auth.signInWithPassword({email:userEmail(f.username.value.trim()),password:f.password.value});if(error||(!isAdmin()&&data.user.id!==post.author_id))throw Error('작성자 아이디 또는 비밀번호가 맞지 않습니다.');await ensureProfile(data.user);updateUser();modal('verifyModal',false);if(verifyTarget.action==='delete'){if(confirm('이 글을 삭제할까요?')){await db.from('posts').delete().eq('id',post.id);render();toast('글을 삭제했습니다.')}}else openPost(post.type,post)}catch(err){$('#verifyError').textContent=err.message||'작성자 확인에 실패했습니다.'}};
const portOptions=[['부산 신항',35.078,128.835],['부산 북항',35.117,129.045],['인천항',37.450,126.593],['평택·당진항',36.973,126.825],['광양항',34.886,127.729],['울산항',35.503,129.392]];
let mapInstance=null,mapMarkers=null,mapTarget='';
function freightInfo(x){if(!x.origin_port)return '';return `<div class="freight-info"><b>${safe(x.origin_port)} → ${safe(x.destination_port)}</b><span>출발 ${safe(x.shipping_date||'-')} · 완료 ${safe(x.deadline_date||'-')}</span><span>인계 ${safe(x.handover_place||'-')} ${safe(x.handover_time||'')}</span><span>화물 ${safe(x.cargo_kind||'-')} · ${safe(x.cargo_amount||'-')}</span></div>`}
function draw(list,empty,items,type){$(list).innerHTML=items.map(x=>{const ownApplications=applications.filter(a=>a.post_id===x.id);return `<article class="card"><span class="tag">${type==='freight'?(x.user_role==='carrier'?'운송 공간':'화물 요청'):safe(x.category)}</span><h3>${safe(x.title)}</h3>${type==='freight'?freightInfo(x):''}<p>${safe(x.content)}</p>${mediaHTML(x.media)}<div class="meta">작성자 ${safe(x.author)}</div><div class="actions">${type==='freight'&&x.author_id!==userId?`<button class="message" data-message="${x.id}">1:1 메시지</button>${freightAction(x)}`:''}${type==='freight'&&x.author_id===userId?`<button data-applications="${x.id}">신청 관리${ownApplications.length?` (${ownApplications.length})`:''}</button>`:''}${x.author_id===userId?`<button data-edit="${x.id}">수정</button><button class="delete" data-delete="${x.id}">삭제</button>`:''}${isAdmin()&&x.author_id!==userId?`<button class="admin-delete" data-admin-delete="${x.id}">관리자 삭제</button>`:''}</div></article>`}).join('');$(list).hidden=!items.length;$(empty).hidden=!!items.length}
function openPost(type,post){const f=$('#postForm'),isFreight=type==='freight';f.reset();f.elements.id.value=post?.id||'';f.dataset.type=type;f.dataset.mediaPath=post?.media_path||'';f.dataset.mediaType=post?.media_type||'';$('#postType').textContent=isFreight?'FREIGHT POST':'COMMUNITY POST';$('#postTitle').textContent=post?'글 수정':isFreight?'모집글 등록':'커뮤니티 글쓰기';$('#categoryWrap').hidden=isFreight;const details=$('#freightDetails');details.hidden=!isFreight;details.querySelectorAll('input').forEach(input=>input.disabled=!isFreight);$('#mediaPreview').innerHTML=mediaHTML(post?.media);$('#mediaError').textContent='';if(post){f.title.value=post.title;f.content.value=post.content;f.category.value=post.category||'질문';['origin_port','destination_port','shipping_date','deadline_date','handover_place','handover_time','cargo_kind','cargo_amount'].forEach(key=>f.elements[key].value=post[key]||'')}modal('postModal',true)}
function openPortMap(target){mapTarget=target;$('#mapTitle').textContent=target==='origin_port'?'출발 항구 선택':'도착 항구 선택';$('#mapError').textContent='';modal('mapModal',true);setTimeout(()=>{if(!mapInstance){mapInstance=L.map('portMap').setView([35.3,128.4],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(mapInstance);mapMarkers=L.layerGroup().addTo(mapInstance)}mapMarkers.clearLayers();portOptions.forEach(([name,lat,lng])=>L.marker([lat,lng]).addTo(mapMarkers).bindPopup(name).on('click',()=>{const field=$('#postForm').elements[mapTarget];field.value=name;modal('mapModal',false);toast(`${name}을(를) 선택했습니다.`)}));mapInstance.invalidateSize()},150)}
document.addEventListener('click',e=>{const mapButton=e.target.closest('[data-map-target]');if(mapButton)openPortMap(mapButton.dataset.mapTarget)});
$('#postForm').onsubmit=async e=>{e.preventDefault();const f=e.target,isFreight=f.dataset.type==='freight';try{if(isFreight&&new Date(f.elements.deadline_date.value)<new Date(f.elements.shipping_date.value))throw Error('배송 완료 기한은 출발일보다 빠를 수 없습니다.');const file=f.elements.media.files[0];let mediaPath=f.dataset.mediaPath||null,mediaType=f.dataset.mediaType||null;if(file){if(!file.type.startsWith('image/')&&!file.type.startsWith('video/'))throw Error('사진 또는 동영상 파일만 올릴 수 있습니다.');if(file.size>3*1024*1024)throw Error('첨부파일은 3MB 이하만 올릴 수 있습니다.');const extension=(file.name.split('.').pop()||'bin').replace(/[^a-zA-Z0-9]/g,'')||'bin';mediaPath=`${userId}/${crypto.randomUUID()}.${extension}`;mediaType=file.type;const {error:uploadError}=await db.storage.from('contact-media').upload(mediaPath,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError}const freightData=isFreight?Object.fromEntries(['origin_port','destination_port','shipping_date','deadline_date','handover_place','handover_time','cargo_kind','cargo_amount'].map(key=>[key,f.elements[key].value.trim?f.elements[key].value.trim():f.elements[key].value])):{origin_port:null,destination_port:null,shipping_date:null,deadline_date:null,handover_place:null,handover_time:null,cargo_kind:null,cargo_amount:null};const data={type:f.dataset.type,user_role:role,category:f.category.value,title:f.title.value.trim(),content:f.content.value.trim(),author_id:userId,media_path:mediaPath,media_type:mediaType,updated_at:new Date().toISOString(),...freightData};let error;if(f.elements.id.value)({error}=await db.from('posts').update(data).eq('id',f.elements.id.value));else({error}=await db.from('posts').insert(data));if(error)throw error;modal('postModal',false);toast('모집 정보를 저장했습니다.');render()}catch(err){$('#mediaError').textContent=err.message||'글을 저장하지 못했습니다.'}};
init();
